[template]
# Define the variables that will be prompted during generation
required = [
    "project-name-kebab",
    "project-display-name", 
    "project-description",
    "project-author",
    "bundle-identifier",
    "project-struct-name"
]

[placeholders.project-name-kebab]
type = "string"
prompt = "Project name (will be used as crate name, in kebab-case)"
default = "iced-app"

[placeholders.project-display-name]
type = "string"
prompt = "Project display name"
default = "Iced App"

[placeholders.project-description]
type = "string"
prompt = "Project description"
default = "A new Iced application"

[placeholders.project-author]
type = "string"
prompt = "Author name"
default = "Your Name"

[placeholders.bundle-identifier]
type = "string"
prompt = "Bundle identifier (e.g., com.yourname.appname)"
default = "com.example.icedapp"

[placeholders.project-struct-name]
type = "string"
prompt = "Main struct name (for the Iced application state)"
default = "IcedApp"

# Configuration for files to exclude from templating (binary files that should be copied as-is)
[template-files]
exclude = [
    "icons/icon.icns",
    "icons/icon.png",
    "icons/icon.iconset/icon_16x16.png",
    "icons/icon.iconset/icon_16x16@2x.png",
    "icons/icon.iconset/icon_32x32.png",
    "icons/icon.iconset/icon_32x32@2x.png",
    "icons/icon.iconset/icon_128x128.png",
    "icons/icon.iconset/icon_128x128@2x.png",
    "icons/icon.iconset/icon_256x256.png",
    "icons/icon.iconset/icon_256x256@2x.png",
]